name: Flask CI

on:
    push:
        branches:
            - master
    pull_request:
            branches: [ master ]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        # Define the steps required to build your application
        steps:
          - name: Checkout Repo for code
            uses: actions/checkout@v4 # $GITHUB_WORKSPACE
          - name: Run a one-line script
            run: |
              echo "Repository checked out successfully"
              ls -la $GITHUB_WORKSPACE
          - name: Set Up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

        # Install dependencies
          - name: Install dependencies
            run: |
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install flask pytest

        # Run tests
          - name: Run tests
            run: |
              pytest > test_results.txt 2>&1 || true
              cat test_results.txt
        
        # Package app as artifact (zip) you can decide to use a different file format than zip tarball(.tar.gz), Plain directory(No compression), Python wheel/package(.whl)
          - name: Package app as artifact
            run: |
              mkdir -p build
              cp -r app.py build/
              zip -r flask_app.zip build/

        # Upload artifact
          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: flask_app
              path: flask_app.zip
            
        # Upload test results separately
          - name: Upload test results
            uses: actions/upload-artifact@v4
            with:
              name: test_results
              path: test_results.txt